### ISSUE TITLE
SQLServer support and cross-compatibility

### ISSUE THREAD

**Issue by SpiraMira** [frapid/frapid#10]
It seems like you also support an IIS/MSSQLServer environment. I am looking to deploy a Frapid based app to Azure Web App Services.

Do you have a guide for setting up SQLServer instead of PostgreSQL?

Also, your website mentions .net cli so cross-compatibility with mac and Linux. Am I correct to assume that I can develop with frapid on macOS using .net core+VisualCode/Xamarin for example...

Thanks in advance,Patrice

**Comment by mixerp** [comment]
Answered on:

https://mixerp.org/forums/thread/528/sql-server-support-for-azure
