### ISSUE TITLE
Can't find Frapid.Core

### ISSUE THREAD

**Issue by esolution911** [frapid/frapid#27]
To build Frapid, below Directory & Solution is not available in Areas

~/src/Frapid.Web/Areas/Frapid.Core/Frapid.Core.sln

where to find it?

**Comment by esolution911** [comment]
Think its in patch-update. let me update.

**Comment by sabja** [comment]
hi,

i think the directory oyu can find it when you open VS, but the solution i haven't found it.

why it's not found if it's so important like that?

**Comment by aswanee** [comment]
me too ?

**Comment by mixerp** [comment]
Frapid.Core module is dropped. AFAIK, you do not need it to build frapid.
