### ISSUE TITLE
SendGrid is not working

### ISSUE THREAD

**Issue by esolution911** [frapid/frapid#28]
I have configured the SendGrid.json as instructed in Install file, but no confirmation email is sent on Sign Up.

User is created in registrations table but without confirmation, there is no other way to login. what to do now?

**Comment by mixerp** [comment]
Hello,

You can use the fields (specially password) present in the registration table and try to insert it manually to users table.

Additionally, you can also investigate if there actually is a row in config.email_queue. If there is one, you can extract activation link from there as well.

Plus, also see the file DomainsApproved.json in github's mixerp/init repository to automate creating users during build or install.

Keep posting!!!

**Comment by esolution911** [comment]
Thanks 

Option 1 worked, i created a row in users table manually and it worked.

no row found in 2nd option.
