### ISSUE TITLE
POS Module with Frapid

### ISSUE THREAD

**Issue by bohece** [frapid/frapid#40]
Hi Binod,

I would like to thank you for the valuable contributions to the ERP ecosystem by your team. MixERP is a great effort with the new revamped Frapid version.

I had a query regarding the paid and community edition modules.
I went through website and then through forums but I am unable to find the clear listing of modules that are not available in the community edition. I am checking the demo, are all of those modules available?

I am specifically interested in only one module for my usage. It is POS module, but I could not find the code.
I saw on forums in the comment below where you have mentioned that it is opensource.
https://mixerp.org/forums/thread/355/we-dont-find-production-crm-pos-modules#1414

Can you please guide me where can I find the POS module?

Regards,
Bohece

**Comment by mixerp** [comment]
Hi,

The modules which have `pro` label on our website are commercial ones.

![image](https://user-images.githubusercontent.com/5273383/31577167-7916c8e8-b129-11e7-91d3-1ca153dacd15.png)

https://mixerp.org/

POS is open source module. Use init project to setup your development environment.

https://www.youtube.com/watch?v=ABnVgWTaVh4&t=2s

I believe that you're able to publish MixERP to your production server all by yourself. If you need help, please don't hesitate to ask.

**Comment by bohece** [comment]
Thanks a lot for the information.
We have started analyzing it. We are seeing it through our test in one of our restaurant.
The POS module has more than required functionality for us. Really excited to use it.

A few questions after the setup:

1. Is there a way to have POS (Add Sales Entry) as an icon added to the dashboard?
To just start taking orders?
2. Why does it show updates in update center even though I took the latest source from github?
![image](https://user-images.githubusercontent.com/32789550/31578074-9221569c-b137-11e7-8d07-b3c82f9363a6.png)
3. All the list pages shows the following on load. Is something wrong with our configuration?
![image](https://user-images.githubusercontent.com/32789550/31578298-177bceae-b13c-11e7-8bf0-5e679e784102.png)
4. How to configure taxes for the items that I sell?
So that it shows state sales tax and country sales tax?
(I referred this: https://mixerp.org/knowledgebase
But cannot find backoffice in any menu)
5. we saw there are predefined selling types like piece, dozen and box. Are those configurable?
Can you please explain what are Attributes, Variants and Item Variants and how to configure these with inventory items?
(Can you please point to the latest documentation where I can see explanation for each module, would be helpful for us?)
6. We were unable to test Addressbook and Calendar.
Both shows the following similar error.
![image](https://user-images.githubusercontent.com/32789550/31578473-7dae7c5a-b13f-11e7-8911-4aa15a76fc80.png)

Sorry for a long questionary, but we are in phase of checking if it is suitable for us.

Regards,
Bohece

**Comment by mixerp** [comment]
1. Currently, no. Workaround is to search for the feature using CTRL + SHIFT + F.
2. Updates are meant to be installed whenever there is one. It is safe to install an update multiple times. It won't delete anything.
3. We've been lazy fixing this issue. For each feature, just enter the dates once, and then the system will remember the dates and this error message will be gone.
4. MixERP only supports a single tax. Depending on your country and requirements, we might be able to create a "Country Pack" for you. If you sponsor the development, we'll be happy to focus on this ASAP.
5. Yes. Use the search feature and find "Units" and "Compound Units". Attributes are item properties which enable you to create an item variant for existing item. For example: iPhone 7 White/Gold/Black. Sorry, we don't have much documentation at this moment. Please ask questions in our forums and we will describe them.
6. You might need to manually open the solutions (AddressBook and Calendar) and build them.

**Comment by bohece** [comment]
Thanks a lot for the information.
I will get in touch on forums
