### ISSUE TITLE
I Have a Question By Debug with a port.

### ISSUE THREAD

**Issue by wadereye** [frapid/frapid#45]
When I Debug the program,I run it on url like http://localhost:55530 ,it makes a port,but the config file in web..config has a key named "DefaultTenant",It can not set value to localhost:55530,and so I can not debug continue,how can i solve this problem?

**Comment by wadereye** [comment]
I change this class  DomainNameExtractor:
public string GetDomain(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
            {
                this.Logger.Information("Cannot extract the domain name because the url was was null.");
                return string.Empty;
            }

            if (url.StartsWith("http"))
            {
                url = url.Replace("http://", "").Replace("https://", "");
            }

            if (url.StartsWith("www."))
            {
                url = url.Replace("www.", "");
            }

            url = url.Split('/').FirstOrDefault() ?? url;

//So I Add a line code like follow:
            url = url.Split(':').FirstOrDefault() ?? url;
            return url;
        }

**Comment by binodnp** [comment]
What happens if the url does not have the `:` character?

**Comment by binodnp** [comment]
Could you please confirm if the change works properly with something like this?

`http://example.com:55530/test`

**Comment by wadereye** [comment]
Thank you!
The Brower will not work if the url does not have the : character,It will show nothing.
and then,I changed the code  let the string like ' http://localhost:55530' to 'http://localhost',so i  solved this problem now Temporary. Thank you again.

**Comment by binodnp** [comment]
Hi,

Please follow these videos, which explain how to use the debugger.

https://www.youtube.com/channel/UCS5Bt00s3_8-o0oI4CLDYDg/featured
